### ISSUE TITLE
Wrong allocation size

### ISSUE THREAD

**Issue by sincos2854** [uyjulian/ifpng#2]
I don't think it will have any impact, but I am reporting it just in case.

LocalAlloc should use sizeof(BITMAPINFO), but sizeof(BITMAPINFOHEADER) is used.
BITMAPINFO is correct in Susie plug-in specification.
An access violation may occur in applications that use Susie plug-in.
However, this problem does not occur because the bit count of the output image is 32.
For all Susie plug-ins.

If you're not too busy, I think it would be nice to have this fixed.
Thank you very much.

**Comment by sincos2854** [comment]
I fixed the following 5 repositories.
Thank you for accepting my pull requests.

ifpng
ifjpeg-turbo
ifwebp
ifavif
ifjxl

Could you please build and release them?

**Comment by uyjulian** [comment]
New versions have been released for all of those.

**Comment by sincos2854** [comment]
Thank you very much.
